circumference_to_pi = "\\frac{x}{1} = pi \\therefore x = pi"
eulers_formula = "e^{i\\theta} = cos({\\theta}) + isin({\\theta})"
eulers_identity = "e^{i\pi} + 1 = 0"
half_pi = "\\frac{pi}{2}"
pi = "{pi}"
pythagorean_theorem = "a^2 + b^2 = c^2 "
reciprocal_x_exponent = "x^{(-1)}"
reciprocal_sin_exponent =  "sin^{(-1)}"
recriprocal_sin_fraction = "\\frac{1}{\sin}"
sin_neg_angle_id = "\\sin(-\\theta)=-\\sin(\\theta)"
square_root_2_over_2 = "\\frac{\sqrt[2]{2}}{2}"
square_root_10 = "\sqrt[2]{10}"
square_root_25 = "\sqrt[2]{25}"
theta = "\\theta"